[package]
name = "stem_winding"
version = "0.0.1"
edition = "2024"
description = "Winding definition for stem - a Simulation Toolbox for Electric Motors."
readme = "README.md"
license  = "MIT OR Apache-2.0"
repository = "https://github.com/StefanMathis/stem_winding.git"

[dependencies]
approxim = { version = "0.6" }
cart_lin = { version = "0.2.1" }
compare_variables = { version = "0.3.0", features = ["proc_macro"] }
deserialize_untagged_verbose_error = { version = "0.1.7", optional = true }
dyn-clone = "1"
embed-doc-image = { version = "0.1.4", optional = true }
keyring_map = "0.1"
num = "0.4.0"
permutation = "0.4.1"
rayon = "1.5"
realfft = "3.5"
serde = { version = "1", features = ["derive"], optional = true }
stem_coil_layout = { path = "../stem_coil_layout" }
serde_mosaic = { version = "0.3", optional = true }
stem_core = { version = "0.1.0", optional = true}
stem_wire = { path = "../stem_wire" } #version = "0.3.0"
typetag = { version = "^0.2", optional = true }

[features]
default = []
stem_core = ["dep:stem_core"]
serde = ["dep:serde_mosaic",
         "dep:deserialize_untagged_verbose_error",
         "dep:serde",
         "dep:typetag",
         "stem_core?/serde",
         "stem_wire/serde",
         "stem_coil_layout/serde",
         "keyring_map/serde"
        ]
cairo = ["stem_core?/cairo"]
doc-images = ["dep:embed-doc-image"]

[dev-dependencies]
serde_mosaic = { version = "0.3", features = ["serde_yaml"] }
indoc = "1.0"
yaml_serde = "0.10.6"
stem_winding = { path = ".", features = ["serde"] }